### ISSUE TITLE
JuliaFinance

### ISSUE THREAD

**Issue by EricForgy** [felipenoris/InterestRates.jl#10]
Hi @felipenoris 👋 

Over the years, I built a private repo for interest rates, but now I've left the company and left the repo behind, which is a shame. I'd like to start doing some more work on interest rate modelling / projections and this package looks like a great place to start. I am just curious, forgive me if I am presumptious, but would you consider forming / joining [JuliaFinance](https://github.com/JuliaFinance) (as an admin) and move this repo to that organization? Absolutely no problem if you don't want to. Just thinking if I am to build some commercial code based on this, it might be better in an organization than an individual. 

Currently, we just have `Currencies.jl`, but we should also have a `Countries.jl` etc. I'm thinking we could start building up a decent warchest for financial engineering. What do you think?

**Comment by felipenoris** [comment]
Yes, I would like that. Actually I tried joining JuliaFinance a few years ago, but got no reply.

**Comment by EricForgy** [comment]
Oh man! So sorry about that. I missed it. I've been an entrepreneur since 2014 and life was a "little" crazy 😅  Would lvoe to have you on JuliaFinance. Let's figure out how to make it happen (I am not a Github expert 😅 )

**Comment by EricForgy** [comment]
Invitation sent 😊

**Comment by felipenoris** [comment]
Nice! Actually, I guess I reached for the wrong person at that time, so it was my fault. Thanks!
